version: "3.8"
services:
  node:
    build: ./app
    container_name: node_app
    expose:
      - "3000"  # Disponibiliza a porta para a rede interna do Docker
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # Mapeia a porta 80 do host para a porta 80 do container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
